/**
 * DEMONSTRATION dataset. Every object here carries isDemo=true and is shown with the
 * "DEMONSTRATION — NOT A REAL SIGHTING" banner. It is never mixed into the real region cache
 * and is never counted as a real record. Place names are fictional.
 */
import type { Claim, Observation, Source, CameraInstallation } from './schemas';
import { SCHEMA_VERSION } from './schemas';
import { createObservation, reviseObservation } from './observation';

export const DEMO_CREATED = '2026-09-14T15:20:00.000Z';

export const DEMO_SOURCE: Source = {
  id: 'demo-src-community',
  kind: 'communityMap',
  title: 'Demonstration community map record (fictional)',
  publisher: 'Sightline demo data',
  url: 'https://www.openstreetmap.org/copyright',
  publishedAt: null,
  accessedAt: '2026-09-14T00:00:00.000Z',
  licenseId: 'ODbL-1.0',
  sourceRecordId: 'demo/1',
  sourceVersion: '1',
  documentPageOrSection: null,
  localSnapshotPath: null,
  snapshotSha256: null,
  availability: 'notChecked',
  attribution: '© OpenStreetMap contributors (ODbL 1.0) — demonstration only',
  retrievalMethod: 'bundled demo fixture',
  scope: 'installation',
};

export const DEMO_PHOTO_SOURCE: Source = {
  ...DEMO_SOURCE,
  id: 'demo-src-photo',
  kind: 'userPhoto',
  title: 'Demonstration photo (synthetic illustration)',
  url: null,
  licenseId: null,
  attribution: 'Synthetic demonstration image generated by Sightline',
  retrievalMethod: 'in-app capture (demo)',
};

export const DEMO_INSTALLATION: CameraInstallation = {
  id: 'demo-installation-1',
  externalIds: [{ namespace: 'demo', elementType: 'node', id: '1', version: '1' }],
  category: 'alpr',
  capabilities: ['plate_recognition'],
  manufacturerId: 'flock',
  familyId: 'flock-lpr',
  modelId: null,
  deploymentMode: 'fixed',
  geometry: { lat: 41.15, lon: -73.25, precisionMeters: null, method: 'source_map', sourceId: DEMO_SOURCE.id },
  orientations: [{ degrees: 90, trueOrMagnetic: 'unknown', sourceId: DEMO_SOURCE.id, quality: 'sourceReported' }],
  operatorClaimIds: [],
  networkClaimIds: [],
  lifecycle: 'reportedPresent',
  firstReportedAt: '2025-11-02T00:00:00.000Z',
  lastObservedAt: '2026-08-21T00:00:00.000Z',
  sourceModifiedAt: '2026-08-21T00:00:00.000Z',
  fetchedAt: '2026-09-14T00:00:00.000Z',
  sourceClaimIds: ['demo-claim-cat', 'demo-claim-mfr'],
  regionIds: ['demo'],
  privateOverrideIds: [],
  isDemo: true,
  schemaVersion: SCHEMA_VERSION,
};

const claim = (id: string, fieldPath: string, value: Claim['value'], sourceId = DEMO_SOURCE.id, basis: Claim['basis'] = 'sourceReported'): Claim => ({
  id,
  subjectId: DEMO_INSTALLATION.id,
  fieldPath,
  value,
  sourceId,
  evidenceAttachmentIds: [],
  basis,
  status: 'unreviewed',
  notes: '',
  validFrom: null,
  validTo: null,
  createdAt: DEMO_CREATED,
  supersedesClaimId: null,
});

export const DEMO_CLAIMS: Claim[] = [
  claim('demo-claim-cat', 'category', 'alpr'),
  claim('demo-claim-mfr', 'hardware.manufacturer', 'Flock Safety'),
  claim('demo-claim-coord', 'location.coordinates', '41.1500,-73.2500'),
  claim('demo-claim-check', 'observation.checkDate', '2026-08-21'),
  claim('demo-claim-observed', 'hardware.mount', 'pole', DEMO_PHOTO_SOURCE.id, 'directlyObserved'),
];

export function demoObservationRevisions(): Observation[] {
  const r1 = createObservation(
    {
      installationId: DEMO_INSTALLATION.id,
      observedAt: '2026-09-14T15:12:00.000Z',
      observedAtBasis: 'device_clock_at_capture',
      deviceTimeZone: 'America/New_York',
      observerLocation: { lat: 41.14905, lon: -73.25102, horizontalAccuracyM: 8, method: 'gps_fix', fixTimestamp: '2026-09-14T15:11:58.000Z' },
      equipmentLocation: { lat: 41.15, lon: -73.25, uncertaintyM: 5, method: 'source_map' },
      distanceSnapshot: { meters: 138, algorithm: 'haversine-r6371008.8', computedAt: '2026-09-14T15:12:00.000Z', referenceKind: 'current_fix', inputsVersion: '1' },
      category: 'alpr',
      candidateFamilyIds: ['flock-lpr', 'motorola-vigilant'],
      selectedFamilyId: 'flock-lpr',
      identificationBasis: 'possible_family_visual_features',
      identificationLevel: 'possible_family',
      features: { mounting: 'pole', form: 'box', visibleText: '', solarPanel: 'yes', apparentOrientation: 'Facing eastbound traffic', categoryReason: 'Matches community map record' },
      placeLabel: 'Example Avenue & Demo Street',
      localNotes: 'DEMO NOTE — private, never exported by default.',
      attachments: ['demo-attachment-1'],
      sources: [DEMO_SOURCE.id, DEMO_PHOTO_SOURCE.id],
      claimIds: DEMO_CLAIMS.map((c) => c.id),
      isDemo: true,
    },
    DEMO_CREATED,
    'demo-observation-1',
  );
  const r2 = reviseObservation(r1, { localNotes: 'DEMO NOTE — private. Added: solar panel visible on top.' }, 'Added note about solar panel', '2026-09-15T09:00:00.000Z');
  return [r1, r2];
}
