/**
 * Evidence ZIP builder (public/sanitized by default) and verifier.
 *
 * Layout (spec §11):
 *   manifest.json
 *   records/observation.json      (public projection only — never DB rows)
 *   records/revisions.json        (revision chain metadata, public-safe fields)
 *   sources/sources.json
 *   media/approved-derivative-*.jpg
 *   report.pdf
 *   report.html                   (parallel accessible report; PDF is untagged)
 *   README.txt
 *   LICENSES.txt
 *   checksums.sha256              (manifest + payload, excluding itself)
 *
 * The manifest lists payload files but not itself. checksums.sha256 includes the exact
 * final manifest bytes and every payload file. The final ZIP hash is computed separately
 * and shown in the export receipt (it cannot be inside the ZIP).
 */
import { strToU8, strFromU8 } from 'fflate';
import type { Attachment, CameraInstallation, Claim, ExportManifest, Observation, Source, Transformation } from './schemas';
import { ExportManifest as ExportManifestSchema, SCHEMA_VERSION } from './schemas';
import { projectPublic, type DisclosureChoices, DEFAULT_DISCLOSURE, LIMITATIONS, DEMO_BANNER, type PublicProjection } from './projection';
import { renderPublicDerivative, hasSensitiveMetadata } from './image';
import { renderReportPdf, renderReportHtml, METHODOLOGY_TEXT } from './report';
import { readZipSafely, writeZipDeterministic, DEFAULT_ZIP_LIMITS, UnsafeArchiveError, type SafeZipLimits } from './safezip';
import { sha256Hex, canonicalJson, uuidv4 } from './hash';

export type DisclosureProfile = ExportManifest['selectedDisclosureProfile'];

export interface EvidencePhotoInput {
  attachment: Pick<Attachment, 'id' | 'sha256' | 'mime' | 'transformations' | 'redactionReviewedAt'>;
  /** Original bytes as stored privately. Only used to render a derivative unless profile is private-full-evidence. */
  originalBytes: Uint8Array;
}

export interface RevisionSummary {
  revision: number;
  revisionHash: string | null;
  previousRevisionHash: string | null;
  recordedAt: string;
  reason: string | null;
}

export interface EvidenceInput {
  observation: Observation;
  sources: Source[];
  claims: Claim[];
  installation: CameraInstallation | null;
  photos: EvidencePhotoInput[];
  revisions: RevisionSummary[];
  choices?: DisclosureChoices;
  profile?: DisclosureProfile;
  /** Must be explicitly true for private-full-evidence (after the in-app review screen). */
  privateFullConfirmed?: boolean;
  observerDistanceText?: string | null;
  createdAt?: string;
  exportId?: string;
}

export interface EvidenceResult {
  zip: Uint8Array;
  zipSha256: string;
  manifest: ExportManifest;
  projection: PublicProjection;
  files: Record<string, Uint8Array>;
}

const README = (p: PublicProjection, profile: DisclosureProfile) =>
  [
    p.demonstration ? `*** ${DEMO_BANNER} ***\nThis package was generated from bundled demonstration data. It does not describe a real sighting.\n` : '',
    'SIGHTLINE EVIDENCE PACKAGE',
    '==========================',
    '',
    `Record: ${p.recordId} (revision ${p.recordRevision})`,
    `Disclosure profile: ${profile}`,
    '',
    'What this package is',
    '--------------------',
    'A machine-readable export of one notebook record from the Sightline app, containing only the',
    'fields the exporter selected. Media files are re-rendered derivatives with metadata removed',
    'unless the profile is "private-full-evidence".',
    '',
    'How to check it',
    '---------------',
    'Recompute SHA-256 for each file and compare with checksums.sha256, or run the bundled',
    'verifier from the Sightline source archive:',
    '',
    '    npx tsx tools/verify-evidence/verify.ts <package.zip>',
    '',
    'A matching result means: "File checksums match this manifest." It does NOT mean the event',
    'is proven authentic. The package is not signed; anyone could alter it and recompute hashes.',
    '',
    'Limitations',
    '-----------',
    ...LIMITATIONS.map((l) => `- ${l}`),
    '',
    'A location report is not proof of recording.',
    '',
  ].join('\n');

const LICENSES = (p: PublicProjection) =>
  [
    'LICENSES AND ATTRIBUTION',
    '========================',
    '',
    'Map/source data:',
    ...(p.attribution.length ? p.attribution.map((a) => `- ${a}`) : ['- No third-party database records included.']),
    '',
    'OpenStreetMap data is available under the Open Database License (ODbL) 1.0:',
    'https://www.openstreetmap.org/copyright — https://opendatacommons.org/licenses/odbl/1-0/',
    '',
    'Photos: taken or imported by the exporter, who is responsible for the rights to share them.',
    'Report and package format generated by Sightline (open source).',
    '',
  ].join('\n');

function json(v: unknown): Uint8Array {
  return strToU8(JSON.stringify(v, null, 2) + '\n');
}

function mimeOf(path: string): string {
  if (path.endsWith('.json')) return 'application/json';
  if (path.endsWith('.jpg')) return 'image/jpeg';
  if (path.endsWith('.png')) return 'image/png';
  if (path.endsWith('.pdf')) return 'application/pdf';
  if (path.endsWith('.html')) return 'text/html';
  if (path.endsWith('.txt') || path.endsWith('.sha256')) return 'text/plain';
  return 'application/octet-stream';
}

export function profileFromChoices(c: DisclosureChoices): DisclosureProfile {
  return c.includeEquipmentCoordinates ? 'public-with-equipment-coordinates' : 'public-default';
}

export async function buildEvidenceZip(input: EvidenceInput): Promise<EvidenceResult> {
  const choices = input.choices ?? DEFAULT_DISCLOSURE;
  const profile = input.profile ?? profileFromChoices(choices);
  if (profile === 'private-full-evidence' && !input.privateFullConfirmed) {
    throw new Error('private-full-evidence requires explicit confirmation after review.');
  }
  const createdAt = input.createdAt ?? new Date().toISOString();
  const projection = projectPublic(
    { observation: input.observation, sources: input.sources, claims: input.claims, installation: input.installation, observerDistanceText: input.observerDistanceText },
    choices,
  );

  const payload: Record<string, Uint8Array> = {};
  const reportPhotos: { name: string; jpeg: Uint8Array; width: number; height: number; sha256: string }[] = [];
  if (choices.includePhoto) {
    input.photos.forEach((ph, i) => {
      const d = renderPublicDerivative(ph.originalBytes, ph.attachment.transformations as Transformation[]);
      const leaks = hasSensitiveMetadata(d.bytes);
      if (leaks.length) throw new Error(`Derivative still contains metadata segments: ${leaks.join(',')}`);
      const name = `media/approved-derivative-${String(i + 1).padStart(2, '0')}.jpg`;
      payload[name] = d.bytes;
      reportPhotos.push({ name, jpeg: d.bytes, width: d.width, height: d.height, sha256: sha256Hex(d.bytes) });
      if (profile === 'private-full-evidence') {
        const ext = ph.attachment.mime === 'image/png' ? 'png' : 'jpg';
        payload[`private/original-${String(i + 1).padStart(2, '0')}.${ext}`] = ph.originalBytes;
      }
    });
  }

  const publicRecord = {
    schemaVersion: SCHEMA_VERSION,
    recordId: projection.recordId,
    recordRevision: projection.recordRevision,
    demonstration: projection.demonstration,
    headline: projection.headline,
    category: projection.category,
    categoryLabel: projection.categoryLabel,
    identification: projection.identification,
    placeLabel: projection.placeLabel,
    observedDate: projection.observedDateText,
    equipmentCoordinates: projection.equipmentCoordinates,
    observerDistance: projection.observerDistanceText,
    sourceStatus: projection.sourceStatus,
    claims: projection.claims,
    limitations: projection.limitations,
    ...(profile === 'private-full-evidence'
      ? {
          privateFullEvidence: {
            warning: 'This section was included by explicit choice and may contain sensitive information.',
            observedAt: input.observation.observedAt,
            observedAtBasis: input.observation.observedAtBasis,
            deviceTimeZone: input.observation.deviceTimeZone,
            observerLocation: input.observation.observerLocation,
            equipmentLocation: input.observation.equipmentLocation,
            localNotes: input.observation.localNotes,
            originalSha256: input.photos.map((p) => p.attachment.sha256),
          },
        }
      : {}),
  };
  payload['records/observation.json'] = json(publicRecord);
  payload['records/revisions.json'] = json({
    note: 'Local revision hash chain (RFC 8785 JCS + SHA-256). It can be rewritten by anyone controlling the device; it is not a trusted timestamp or authenticated chain of custody.',
    revisions: input.revisions.map((r) => ({
      revision: r.revision,
      revisionHash: r.revisionHash,
      previousRevisionHash: r.previousRevisionHash,
      recordedAt: profile === 'private-full-evidence' ? r.recordedAt : r.recordedAt.slice(0, 7),
      reason: profile === 'private-full-evidence' ? r.reason : null,
    })),
  });
  payload['sources/sources.json'] = json({ sources: projection.sources });

  // Report checksums cover media + records; the report cannot contain its own hash.
  const preReportChecksums = Object.keys(payload)
    .sort()
    .map((p) => ({ path: p, sha256: sha256Hex(payload[p]) }));
  const chronology = [
    ...(projection.observedDateText ? [{ when: projection.observedDateText, what: 'Observation recorded on device (device clock; not independently attested).' }] : []),
    ...input.revisions.map((r) => ({ when: r.recordedAt.slice(0, 10), what: `Revision ${r.revision}${r.reason && profile === 'private-full-evidence' ? ` — ${r.reason}` : ''}` })),
    { when: createdAt.slice(0, 10), what: `Evidence package exported (profile: ${profile}).` },
  ];
  const reportInput = {
    projection,
    photos: reportPhotos,
    chronology,
    methodology: METHODOLOGY_TEXT,
    checksums: preReportChecksums,
    generatedAtText: `${createdAt.replace('T', ' ').slice(0, 16)} UTC`,
  };
  payload['report.pdf'] = await renderReportPdf(reportInput);
  payload['report.html'] = strToU8(renderReportHtml(reportInput, reportPhotos.map((p) => p.name)));
  payload['README.txt'] = strToU8(README(projection, profile));
  payload['LICENSES.txt'] = strToU8(LICENSES(projection));

  const fileEntries = Object.keys(payload)
    .sort()
    .map((p) => ({ relativePath: p, mime: mimeOf(p), bytes: payload[p].length, sha256: sha256Hex(payload[p]) }));
  const manifest: ExportManifest = ExportManifestSchema.parse({
    schemaVersion: SCHEMA_VERSION,
    format: 'sightline-evidence',
    exportId: input.exportId ?? uuidv4(),
    recordId: projection.recordId,
    recordRevision: projection.recordRevision,
    exportCreatedAt: createdAt,
    selectedDisclosureProfile: profile,
    exportedClaims: projection.claims,
    sourceRefs: projection.sources.map((s) => ({ id: s.id, title: s.title, url: s.url, accessedAt: s.accessedAt, licenseId: s.licenseId })),
    limitations: LIMITATIONS,
    files: fileEntries,
    attribution: projection.attribution,
    derivedFromRecordDigest: input.observation.revisionHash ?? null,
    demonstration: projection.demonstration,
  });
  const manifestBytes = json(manifest);
  const files: Record<string, Uint8Array> = { ...payload, 'manifest.json': manifestBytes };
  const checksumLines = Object.keys(files)
    .sort()
    .map((p) => `${sha256Hex(files[p])}  ${p}`)
    .join('\n');
  files['checksums.sha256'] = strToU8(checksumLines + '\n');
  const zip = writeZipDeterministic(files);
  return { zip, zipSha256: sha256Hex(zip), manifest, projection, files };
}

// ---------------------------------------------------------------- verification

export type VerifyStatus = 'match' | 'mismatch' | 'unsafe' | 'unsupported' | 'malformed';

export interface VerifyReport {
  status: VerifyStatus;
  headline: string;
  details: string[];
  manifest: ExportManifest | null;
  zipSha256: string;
  checkedFiles: number;
  demonstration: boolean;
}

export const VERIFY_EXPLANATION =
  'A match means the files are unchanged relative to this manifest. It does not prove the scene, time, location or claim is true, and an unsigned package can be replaced and re-hashed by someone else.';

export function verifyEvidenceZip(data: Uint8Array, limits: SafeZipLimits = DEFAULT_ZIP_LIMITS): VerifyReport {
  const zipSha256 = sha256Hex(data);
  const base = { manifest: null, zipSha256, checkedFiles: 0, demonstration: false };
  let entries: Map<string, Uint8Array>;
  try {
    entries = readZipSafely(data, limits);
  } catch (e) {
    if (e instanceof UnsafeArchiveError) return { ...base, status: 'unsafe', headline: 'Archive rejected as unsafe', details: [`${e.code}: ${e.message}`] };
    return { ...base, status: 'malformed', headline: 'Not a readable ZIP archive', details: [String((e as Error).message)] };
  }
  const mBytes = entries.get('manifest.json');
  if (!mBytes) return { ...base, status: 'malformed', headline: 'manifest.json is missing', details: [] };
  let raw: unknown;
  try {
    raw = JSON.parse(strFromU8(mBytes));
  } catch {
    return { ...base, status: 'malformed', headline: 'manifest.json is not valid JSON', details: [] };
  }
  const r = raw as { schemaVersion?: unknown; format?: unknown };
  if (r?.format !== 'sightline-evidence') return { ...base, status: 'unsupported', headline: 'Not a Sightline evidence package', details: [`format: ${String(r?.format)}`] };
  if (r.schemaVersion !== SCHEMA_VERSION) return { ...base, status: 'unsupported', headline: `Unknown schema version ${String(r.schemaVersion)}`, details: [`This verifier supports schema version ${SCHEMA_VERSION}.`] };
  const parsed = ExportManifestSchema.safeParse(raw);
  if (!parsed.success) return { ...base, status: 'malformed', headline: 'manifest.json does not match the schema', details: parsed.error.issues.slice(0, 5).map((i) => `${i.path.join('.')}: ${i.message}`) };
  const manifest = parsed.data;
  const details: string[] = [];
  let ok = true;
  const listed = new Set<string>();
  for (const f of manifest.files) {
    listed.add(f.relativePath);
    const b = entries.get(f.relativePath);
    if (!b) {
      ok = false;
      details.push(`MISSING ${f.relativePath}`);
      continue;
    }
    const h = sha256Hex(b);
    if (h !== f.sha256 || b.length !== f.bytes) {
      ok = false;
      details.push(`CHANGED ${f.relativePath}`);
    } else details.push(`OK ${f.relativePath}`);
  }
  for (const name of entries.keys()) {
    if (name === 'manifest.json' || name === 'checksums.sha256') continue;
    if (!listed.has(name)) {
      ok = false;
      details.push(`UNLISTED ${name}`);
    }
  }
  const sums = entries.get('checksums.sha256');
  if (!sums) {
    ok = false;
    details.push('MISSING checksums.sha256');
  } else {
    const lines = strFromU8(sums).trim().split('\n');
    const map = new Map(lines.map((l) => [l.slice(66), l.slice(0, 64)]));
    const mh = map.get('manifest.json');
    if (mh !== sha256Hex(mBytes)) {
      ok = false;
      details.push('CHANGED manifest.json (does not match checksums.sha256)');
    } else details.push('OK manifest.json');
    for (const f of manifest.files) if (map.get(f.relativePath) !== f.sha256) {
      ok = false;
      details.push(`CHECKSUM-LIST MISMATCH ${f.relativePath}`);
    }
  }
  return {
    status: ok ? 'match' : 'mismatch',
    headline: ok ? 'File checksums match this manifest' : 'File checksums do NOT match this manifest',
    details,
    manifest,
    zipSha256,
    checkedFiles: manifest.files.length,
    demonstration: manifest.demonstration,
  };
}

export { canonicalJson };
