/**
 * Equipment field guide. Data-driven; add families without redesigning screens.
 * Capability text = manufacturer descriptions, not independent validation and not a fact
 * about any installed device. Schematic ids refer to original line drawings in src/design/schematics.tsx.
 */
import type { CatalogEntry } from '../../src/domain/schemas';

const APPEARANCE_CANNOT_TELL = [
  'Who operates it or who can search its data',
  'How long data is retained or with whom it is shared',
  'Whether it is connected to an integration platform (e.g., Fusus, FlockOS)',
  'Whether it is powered, recording or functioning now',
  'Whether it read any particular plate or recorded any person',
  'Whether its placement or use is lawful',
];

type E = Omit<CatalogEntry, 'unknowns'> & { unknowns?: string[] };
const e = (x: E): CatalogEntry => ({ ...x, unknowns: [...(x.unknowns ?? []), ...APPEARANCE_CANNOT_TELL] });

export const CATALOG: CatalogEntry[] = [
  e({
    id: 'flock-lpr',
    manufacturer: 'Flock Safety',
    familyLabel: 'Flock license plate readers',
    currentLabels: ['Standard LPR', 'Wide-Range LPR', 'Long-Range LPR', 'Flex LPR'],
    legacyAliases: ['Falcon', 'Falcon LR', 'Falcon SR', 'Falcon Flex', 'Sparrow'],
    category: 'alpr',
    deploymentModes: ['fixed', 'relocatable'],
    kind: 'physical_device',
    summary: 'Fixed or relocatable automated plate and vehicle recognition cameras marketed by Flock Safety.',
    whatItDoes: 'Flock describes its LPR products as capturing images of vehicles and converting plates and vehicle characteristics into searchable data. Current marketing uses labels such as Standard, Wide-Range, Long-Range and Flex LPR. Older contracts and community maps use Falcon/Sparrow names; Sightline does not assume a one-to-one mapping between old and new labels without documentation.',
    visibleCues: ['Compact box-shaped housing on its own pole or existing pole', 'Often a small solar panel mounted above the camera', 'Typically aimed along a roadway at vehicle height'],
    confirmedFeatures: ['Plate/vehicle recognition is the marketed purpose of the family'],
    lookalikes: ['Traffic-counting cameras', 'Other vendors\u2019 solar ALPR units', 'Generic solar-powered CCTV'],
    distinguishers: ['Readable Flock branding or a model label', 'A public deployment record (contract, map, agency document) for that exact spot'],
    matchHints: { mounting: ['pole', 'streetlight'], form: ['box', 'bullet'], solar: 'common', textPatterns: ['flock', 'falcon', 'sparrow'] },
    sourceIds: ['C1', 'C2', 'C3a', 'C3b'],
    schematic: 'solar-box-pole',
  }),
  e({
    id: 'flock-video',
    manufacturer: 'Flock Safety',
    familyLabel: 'Flock video cameras',
    currentLabels: ['Video Cameras'],
    legacyAliases: ['Condor'],
    category: 'video',
    deploymentModes: ['fixed', 'relocatable'],
    kind: 'physical_device',
    summary: 'Video surveillance cameras; kept separate from dedicated plate-reader classification.',
    whatItDoes: 'Flock markets a video camera line (the legacy Condor URL resolves into this category). Sightline classifies these as video unless a deployment source for a specific site also establishes plate recognition.',
    visibleCues: ['Dome or bullet video housing', 'May share a pole with other equipment'],
    confirmedFeatures: ['Video surveillance is the marketed category'],
    lookalikes: ['Any municipal or private CCTV'],
    distinguishers: ['Readable branding or model label', 'A site-specific deployment record'],
    matchHints: { mounting: ['pole', 'building', 'streetlight'], form: ['dome', 'bullet', 'multi_lens'], solar: 'any', textPatterns: ['flock', 'condor'] },
    sourceIds: ['C4'],
    schematic: 'dome-pole',
  }),
  e({
    id: 'flock-gunshot',
    manufacturer: 'Flock Safety',
    familyLabel: 'Flock gunshot / audio detection',
    currentLabels: ['Gunshot Detection'],
    legacyAliases: ['Raven'],
    category: 'acoustic',
    deploymentModes: ['fixed'],
    kind: 'physical_device',
    summary: 'An acoustic sensor, not a camera.',
    whatItDoes: 'Flock describes this product as acoustic detection of events such as gunfire; a 2026 Flock explainer identifies Raven as its former name. Sightline does not carry forward older audio-capability claims as current facts.',
    visibleCues: ['Small sensor enclosure, often on a pole or building', 'No visible lens'],
    confirmedFeatures: ['Marketed as acoustic detection'],
    unknowns: ['What audio is processed or retained at any site'],
    lookalikes: ['Weather or air-quality sensors', 'Network radios', 'Other acoustic sensors'],
    distinguishers: ['Readable label', 'Agency deployment record'],
    matchHints: { mounting: ['pole', 'building', 'streetlight'], form: ['sensor'], solar: 'any', textPatterns: ['raven', 'flock'] },
    sourceIds: ['C5a', 'C5b'],
    schematic: 'sensor-box',
  }),
  e({
    id: 'flock-trailer-drone',
    manufacturer: 'Flock Safety',
    familyLabel: 'Flock trailers and drone programs',
    currentLabels: ['Trailers', 'Drone programs'],
    legacyAliases: [],
    category: 'unknown',
    deploymentModes: ['trailer'],
    kind: 'deployment_form',
    summary: 'A trailer is a mounting/deployment form, not a new sensing capability. Drone adoption belongs in agency context.',
    whatItDoes: 'Flock\u2019s product hub lists trailers and drone offerings. Sightline records a trailer sighting as a dated observation and classifies the sensors on it separately. There is no live aircraft map.',
    visibleCues: ['Towable trailer with a mast, cameras and solar panels'],
    confirmedFeatures: [],
    lookalikes: ['Other vendors\u2019 mobile surveillance trailers', 'Construction-site camera towers'],
    distinguishers: ['Readable branding', 'A dated public notice'],
    matchHints: { mounting: ['trailer'], form: ['multi_lens', 'box', 'dome'], solar: 'common', textPatterns: ['flock'] },
    sourceIds: ['C1'],
    schematic: 'trailer',
  }),
  e({
    id: 'axon-outpost',
    manufacturer: 'Axon',
    familyLabel: 'Axon Outpost',
    currentLabels: ['Outpost'],
    legacyAliases: [],
    category: 'alpr',
    deploymentModes: ['fixed', 'relocatable'],
    kind: 'physical_device',
    summary: 'Infrastructure camera that, according to Axon, combines ALPR, video and vehicle attributes.',
    whatItDoes: 'Axon markets Outpost as an infrastructure camera combining plate recognition, video and vehicle-attribute features.',
    visibleCues: ['Pole-mounted housing, may include solar power'],
    confirmedFeatures: ['Marketed as ALPR + video + vehicle attributes'],
    lookalikes: ['Flock LPR', 'Other solar ALPR units'],
    distinguishers: ['Readable Axon branding', 'Deployment record'],
    matchHints: { mounting: ['pole'], form: ['box', 'multi_lens'], solar: 'common', textPatterns: ['axon', 'outpost'] },
    sourceIds: ['C6'],
    schematic: 'solar-box-pole',
  }),
  e({
    id: 'axon-lightpost',
    manufacturer: 'Axon',
    familyLabel: 'Axon Lightpost',
    currentLabels: ['Lightpost'],
    legacyAliases: [],
    category: 'alpr',
    deploymentModes: ['fixed'],
    kind: 'physical_device',
    summary: 'Streetlight-integrated camera with ALPR/video/vehicle attributes, according to Axon.',
    whatItDoes: 'Axon markets Lightpost as a camera that mounts on streetlights and provides plate recognition, video and vehicle attributes.',
    visibleCues: ['Housing attached to a streetlight arm or pole'],
    confirmedFeatures: ['Marketed as streetlight-mounted ALPR + video'],
    lookalikes: ['Streetlight sensor nodes', 'Smart-city lighting controllers'],
    distinguishers: ['Readable label', 'Deployment record'],
    matchHints: { mounting: ['streetlight'], form: ['box', 'bullet'], solar: 'rare', textPatterns: ['axon', 'lightpost'] },
    sourceIds: ['C7'],
    schematic: 'streetlight',
  }),
  e({
    id: 'axon-fleet3',
    manufacturer: 'Axon',
    familyLabel: 'Axon Fleet 3',
    currentLabels: ['Fleet 3'],
    legacyAliases: [],
    category: 'alpr',
    deploymentModes: ['vehicle_mounted'],
    kind: 'physical_device',
    summary: 'Vehicle-mounted video with mobile ALPR. A dated sighting is not a fixed installation.',
    whatItDoes: 'Axon describes Fleet 3 as an in-car video system with an ALPR capability. Sightline records vehicle sightings as dated, historical observations and excludes them from the fixed-infrastructure layer by default.',
    visibleCues: ['Cameras inside the windshield or on a patrol vehicle light bar'],
    confirmedFeatures: ['Marketed as in-car video with ALPR'],
    lookalikes: ['Dashcams', 'Other mobile ALPR kits'],
    distinguishers: ['Agency fleet documentation'],
    matchHints: { mounting: ['vehicle'], form: ['box', 'bullet', 'unknown'], solar: 'rare', textPatterns: ['axon', 'fleet'] },
    sourceIds: ['C8a', 'C8b'],
    schematic: 'vehicle',
  }),
  e({
    id: 'axon-fusus',
    manufacturer: 'Axon',
    familyLabel: 'Axon Fusus',
    currentLabels: ['Fusus'],
    legacyAliases: ['FususONE', 'FususCORE'],
    category: 'unknown',
    deploymentModes: ['unknown'],
    kind: 'software_or_platform',
    summary: 'An integration platform, not a distinctive camera housing.',
    whatItDoes: 'Axon describes Fusus as a platform that can connect cameras and feeds, including other manufacturers\u2019 cameras. Visual appearance alone cannot establish that any camera is connected to Fusus.',
    visibleCues: ['None reliable — a connection is not visible'],
    confirmedFeatures: [],
    lookalikes: ['Any camera'],
    distinguishers: ['A registration program, contract or agency document'],
    matchHints: { mounting: [], form: [], solar: 'any', textPatterns: ['fusus'] },
    sourceIds: ['C9'],
    schematic: 'network',
  }),
  e({
    id: 'motorola-vigilant',
    manufacturer: 'Motorola Solutions / Vigilant',
    familyLabel: 'Vigilant L5F and L6Q',
    currentLabels: ['L5F', 'L6Q'],
    legacyAliases: ['Vigilant Solutions'],
    category: 'alpr',
    deploymentModes: ['fixed', 'relocatable'],
    kind: 'physical_device',
    summary: 'Fixed (L5F) and quick-deploy (L6Q) ALPR camera families.',
    whatItDoes: 'Motorola Solutions markets L5F as a fixed LPR camera system and L6Q as a quick-deploy LPR. Software brands such as VehicleManager are not physical camera shapes.',
    visibleCues: ['Box housing on a pole or mast', 'Quick-deploy units may be battery/solar powered'],
    confirmedFeatures: ['Marketed as fixed and quick-deploy LPR'],
    lookalikes: ['Other fixed ALPR units'],
    distinguishers: ['Readable label', 'Deployment record'],
    matchHints: { mounting: ['pole', 'gantry'], form: ['box', 'bullet'], solar: 'any', textPatterns: ['motorola', 'vigilant', 'l5f', 'l6q'] },
    sourceIds: ['C10', 'C11'],
    schematic: 'box-pole',
  }),
  e({
    id: 'genetec-autovu',
    manufacturer: 'Genetec',
    familyLabel: 'Genetec AutoVu',
    currentLabels: ['AutoVu SharpV', 'AutoVu SharpZ3', 'AutoVu Cloudrunner'],
    legacyAliases: [],
    category: 'alpr',
    deploymentModes: ['fixed', 'vehicle_mounted', 'relocatable'],
    kind: 'physical_device',
    summary: 'Fixed, mobile and deployment options within the AutoVu ALPR ecosystem.',
    whatItDoes: 'Genetec markets AutoVu as an ALPR family including fixed (SharpV), vehicle-mounted (SharpZ3) and Cloudrunner options. Sightline keeps model, software and mounting as separate fields.',
    visibleCues: ['Fixed box camera, vehicle roof units, or compact solar units'],
    confirmedFeatures: ['Marketed as ALPR'],
    lookalikes: ['Other ALPR units'],
    distinguishers: ['Readable label', 'Deployment record'],
    matchHints: { mounting: ['pole', 'vehicle', 'gantry', 'building'], form: ['box', 'bullet'], solar: 'any', textPatterns: ['genetec', 'autovu', 'sharp', 'cloudrunner'] },
    sourceIds: ['C12'],
    schematic: 'box-pole',
  }),
  e({
    id: 'leonardo-elsag',
    manufacturer: 'Leonardo / ELSAG',
    familyLabel: 'ELSAG plate readers',
    currentLabels: ['Fixed Plate Hunter', 'Street Sentry', 'Mobile Plate Hunter', 'VPH900'],
    legacyAliases: ['ELSAG'],
    category: 'alpr',
    deploymentModes: ['fixed', 'vehicle_mounted', 'relocatable'],
    kind: 'physical_device',
    summary: 'Fixed, solar, mobile and video-based plate recognition families.',
    whatItDoes: 'Leonardo markets ELSAG Fixed Plate Hunter and Street Sentry (fixed/solar), Mobile Plate Hunter (vehicle) and VPH900 (video-based recognition).',
    visibleCues: ['Fixed box cameras on poles; vehicle roof-mounted units'],
    confirmedFeatures: ['Marketed as plate recognition'],
    lookalikes: ['Other ALPR units'],
    distinguishers: ['Readable label', 'Deployment record'],
    matchHints: { mounting: ['pole', 'vehicle', 'gantry'], form: ['box', 'bullet'], solar: 'any', textPatterns: ['elsag', 'leonardo', 'plate hunter', 'street sentry', 'vph'] },
    sourceIds: ['C13', 'C14a', 'C14b'],
    schematic: 'box-pole',
  }),
  e({
    id: 'rekor',
    manufacturer: 'Rekor',
    familyLabel: 'Rekor Edge and Scout',
    currentLabels: ['Edge Pro', 'Edge Max', 'Scout'],
    legacyAliases: ['OpenALPR'],
    category: 'alpr',
    deploymentModes: ['fixed', 'unknown'],
    kind: 'physical_device',
    summary: 'Hardware plus software recognition that may run on existing IP cameras.',
    whatItDoes: 'Rekor markets Edge Pro and Edge Max hardware and Scout software, which its documentation describes as processing video from IP cameras. Because recognition can be software on an ordinary camera, appearance is not a reliable identifier.',
    visibleCues: ['Edge units: compact camera housings', 'Scout: any IP camera'],
    confirmedFeatures: ['Marketed as plate recognition'],
    lookalikes: ['Any IP camera'],
    distinguishers: ['Contract/procurement records'],
    matchHints: { mounting: ['pole', 'building'], form: ['box', 'bullet'], solar: 'any', textPatterns: ['rekor', 'openalpr', 'edge'] },
    sourceIds: ['C15', 'C16', 'C17'],
    schematic: 'box-pole',
  }),
  e({
    id: 'neology',
    manufacturer: 'Neology',
    familyLabel: 'Neology ANPR',
    currentLabels: ['neoForce', 'P497', 'P720'],
    legacyAliases: [],
    category: 'alpr',
    deploymentModes: ['fixed', 'vehicle_mounted'],
    kind: 'physical_device',
    summary: 'Fixed and mobile ANPR families.',
    whatItDoes: 'Neology markets neoForce and P497 cameras and a P720 mobile enforcement system for plate recognition.',
    visibleCues: ['Fixed camera housings; vehicle-mounted units'],
    confirmedFeatures: ['Marketed as ANPR'],
    lookalikes: ['Other ALPR units'],
    distinguishers: ['Readable label', 'Deployment record'],
    matchHints: { mounting: ['pole', 'gantry', 'vehicle'], form: ['box', 'bullet'], solar: 'any', textPatterns: ['neology', 'neoforce', 'p497', 'p720'] },
    sourceIds: ['C18', 'C19', 'C20'],
    schematic: 'box-pole',
  }),
  e({
    id: 'jenoptik-vector',
    manufacturer: 'Jenoptik',
    familyLabel: 'Jenoptik VECTOR',
    currentLabels: ['VECTOR2', 'VECTOR3'],
    legacyAliases: ['VECTOR\u00b2', 'VECTOR\u00b3'],
    category: 'alpr',
    deploymentModes: ['fixed'],
    kind: 'physical_device',
    summary: 'ANPR camera family; aliases and geographic availability vary.',
    whatItDoes: 'Jenoptik markets VECTOR-series cameras for plate recognition. Check documented geographic applicability before assuming a model is sold in the U.S.',
    visibleCues: ['Compact housings on gantries or poles'],
    confirmedFeatures: ['Marketed as ANPR'],
    lookalikes: ['Enforcement cameras', 'Other ANPR'],
    distinguishers: ['Readable label', 'Deployment record'],
    matchHints: { mounting: ['gantry', 'pole'], form: ['box'], solar: 'rare', textPatterns: ['jenoptik', 'vector'] },
    sourceIds: ['C21a', 'C21b'],
    schematic: 'gantry',
  }),
  e({
    id: 'axis-q1800',
    manufacturer: 'Axis Communications',
    familyLabel: 'Axis Q1800-LE / License Plate Verifier',
    currentLabels: ['Q1800-LE', 'Q1800-LE-3', 'License Plate Verifier'],
    legacyAliases: [],
    category: 'video',
    deploymentModes: ['fixed'],
    kind: 'physical_device',
    summary: 'Camera hardware and an installable recognition application are distinct. An Axis logo alone does not establish ALPR.',
    whatItDoes: 'Axis sells Q1800-LE bullet cameras and a License Plate Verifier kit/application. Sightline classifies an Axis camera as video unless documentation establishes plate recognition at the site.',
    visibleCues: ['Bullet camera with integrated sunshield'],
    confirmedFeatures: [],
    lookalikes: ['Other bullet CCTV'],
    distinguishers: ['Documentation of the installed application'],
    matchHints: { mounting: ['pole', 'building'], form: ['bullet'], solar: 'rare', textPatterns: ['axis', 'q1800'] },
    sourceIds: ['C22'],
    schematic: 'bullet-pole',
  }),
  e({
    id: 'hanwha-road-ai',
    manufacturer: 'Hanwha Vision / Wisenet',
    familyLabel: 'Wisenet Road AI ecosystem',
    currentLabels: ['Road AI'],
    legacyAliases: ['Hanwha Techwin'],
    category: 'video',
    deploymentModes: ['fixed'],
    kind: 'software_or_platform',
    summary: 'Video/vehicle-recognition ecosystem; not every Hanwha camera is a plate reader.',
    whatItDoes: 'Hanwha announced Wisenet Road AI as an LPR solution using compatible cameras. Sightline does not label every Hanwha camera as a plate reader.',
    visibleCues: ['Wisenet-branded bullet or box cameras'],
    confirmedFeatures: [],
    lookalikes: ['Any Wisenet CCTV'],
    distinguishers: ['Documentation of the installed solution'],
    matchHints: { mounting: ['pole', 'building'], form: ['bullet', 'box'], solar: 'rare', textPatterns: ['wisenet', 'hanwha'] },
    sourceIds: ['C23'],
    schematic: 'bullet-pole',
  }),
  e({
    id: 'enforcement-cameras',
    manufacturer: 'Verra Mobility; Sensys Gatso',
    familyLabel: 'Red-light, speed and school-zone enforcement cameras',
    currentLabels: ['Red-light', 'Speed', 'School-zone', 'School-bus stop-arm'],
    legacyAliases: ['American Traffic Solutions (ATS)', 'Redflex'],
    category: 'enforcement',
    deploymentModes: ['fixed', 'relocatable', 'vehicle_mounted'],
    kind: 'physical_device',
    summary: 'Automated enforcement is a different purpose from general ALPR investigation, although capabilities can overlap.',
    whatItDoes: 'Verra Mobility and Sensys Gatso market documented enforcement programs such as red-light and speed cameras. These usually operate under specific statutes and programs.',
    visibleCues: ['Large cabinets or pole-mounted cameras at intersections', 'Flash units', 'Posted enforcement signage'],
    confirmedFeatures: ['Marketed as traffic enforcement'],
    lookalikes: ['Traffic-monitoring cameras', 'ALPR'],
    distinguishers: ['Posted signage', 'Municipal program records'],
    matchHints: { mounting: ['pole', 'gantry', 'vehicle'], form: ['box'], solar: 'rare', textPatterns: ['verra', 'gatso', 'redflex', 'photo enforced', 'speed camera'] },
    sourceIds: ['C24', 'C25'],
    schematic: 'gantry',
  }),
  e({
    id: 'shotspotter',
    manufacturer: 'SoundThinking',
    familyLabel: 'ShotSpotter',
    currentLabels: ['ShotSpotter'],
    legacyAliases: ['ShotSpotter Inc.'],
    category: 'acoustic',
    deploymentModes: ['fixed'],
    kind: 'physical_device',
    summary: 'An acoustic detection system, not a camera.',
    whatItDoes: 'SoundThinking describes ShotSpotter as an acoustic gunshot detection system using sensors placed in an area.',
    visibleCues: ['Small sensor enclosures on buildings or poles', 'No lens'],
    confirmedFeatures: ['Marketed as acoustic detection'],
    lookalikes: ['Other sensors and radios'],
    distinguishers: ['Agency contract records'],
    matchHints: { mounting: ['pole', 'building'], form: ['sensor'], solar: 'any', textPatterns: ['shotspotter', 'soundthinking'] },
    sourceIds: ['C26'],
    schematic: 'sensor-box',
  }),
  e({
    id: 'generic-unknown',
    manufacturer: 'Unknown / other',
    familyLabel: 'Unknown or generic equipment',
    currentLabels: ['Fixed CCTV', 'PTZ', 'Multi-sensor', 'Traffic monitoring', 'Parking / access control', 'Unknown sensor'],
    legacyAliases: [],
    category: 'unknown',
    deploymentModes: ['fixed', 'unknown'],
    kind: 'generic',
    summary: 'Generic classification with an unknown vendor is a first-class, valid result.',
    whatItDoes: 'Many public-facing cameras and sensors cannot be identified from the street. Recording a generic type with "vendor unknown" is accurate and useful.',
    visibleCues: ['Domes, bullets, PTZ housings, multi-lens heads, unlabelled boxes'],
    confirmedFeatures: [],
    lookalikes: [],
    distinguishers: ['Labels, documents or public records'],
    matchHints: { mounting: ['pole', 'building', 'streetlight', 'gantry', 'other'], form: ['dome', 'bullet', 'multi_lens', 'box', 'sensor', 'unknown'], solar: 'any', textPatterns: [] },
    sourceIds: ['D3'],
    schematic: 'dome-pole',
  }),
];

export const CATALOG_BY_ID: Record<string, CatalogEntry> = Object.fromEntries(CATALOG.map((c) => [c.id, c]));

export const MANUFACTURER_TO_FAMILIES: Record<string, string[]> = {
  flock: ['flock-lpr', 'flock-video', 'flock-gunshot', 'flock-trailer-drone'],
  axon: ['axon-outpost', 'axon-lightpost', 'axon-fleet3', 'axon-fusus'],
  motorola: ['motorola-vigilant'],
  genetec: ['genetec-autovu'],
  leonardo: ['leonardo-elsag'],
  rekor: ['rekor'],
  neology: ['neology'],
  jenoptik: ['jenoptik-vector'],
  axis: ['axis-q1800'],
  hanwha: ['hanwha-road-ai'],
  verra: ['enforcement-cameras'],
  'sensys-gatso': ['enforcement-cameras'],
  soundthinking: ['shotspotter'],
};

export const MANUFACTURER_LABEL: Record<string, string> = {
  flock: 'Flock Safety',
  axon: 'Axon',
  motorola: 'Motorola Solutions / Vigilant',
  genetec: 'Genetec',
  leonardo: 'Leonardo / ELSAG',
  rekor: 'Rekor',
  neology: 'Neology',
  jenoptik: 'Jenoptik',
  axis: 'Axis Communications',
  hanwha: 'Hanwha Vision',
  verra: 'Verra Mobility',
  'sensys-gatso': 'Sensys Gatso',
  soundthinking: 'SoundThinking',
};
