/**
 * State laws that specifically regulate automated license-plate readers (ALPRs).
 * Researched 2026-10-06 (docs/LEGAL_REVIEW.md). Summaries are plain-language and partial; read the
 * statute. A state missing here may still regulate ALPRs through other law, policy or regulation.
 */
export interface AlprLaw {
  code: string;
  state: string;
  statute: string;
  summary: string;
  retention: string;
  url: string;
  verified: boolean;
}

export const ALPR_LAWS: AlprLaw[] = [
  {code: "AL", state: "Alabama", statute: "Ala. Admin. Code ch. 265-X-6 (Alabama Justice Information Commission rule, eff. 3/17/2022)", summary: "An agency rule, not a statute. Police may collect ALPR data only for criminal justice or public safety. Data must go to a secure agency repository within 24 hours and a state registry within 48 hours. Searches are logged and agencies need policies.", retention: "Up to 5 years (longer for active investigations or pending cases)", url: "https://admincode.legislature.state.al.us/api/chapter/265-X-6", verified: true},
  {code: "AR", state: "Arkansas", statute: "Ark. Code Ann. §§ 12-12-1801 to -1808 (as amended by Act 668 of 2025)", summary: "Anyone, including private people, may use ALPRs only within listed exceptions: police database checks, parking, secured-area access, weigh stations, and (since 2025) private owners on their own property. Data can't be used or shared for other purposes. Government may not sell it. Private vendor contracts must cap retention at 60 days.", retention: "150 days (government/eligible entities); 60 days (private landowners/businesses); longer for ongoing investigations", url: "https://arkleg.state.ar.us/Home/FTPDocument?path=%2FACTS%2F2025R%2FPublic%2FACT668.pdf", verified: true},
  {code: "CA", state: "California", statute: "Cal. Civ. Code §§ 1798.90.5–1798.90.55 (SB 34, 2015); Cal. Veh. Code § 2413 (CHP)", summary: "All public and private ALPR operators and end-users must keep reasonable security and post a usage and privacy policy covering purposes, access, sharing and retention. Public agencies must hold public comment before starting a program and may share data only with other public agencies. People harmed by violations can sue.", retention: "No fixed statewide limit; each operator sets its own in its required policy. CHP only: 60 days (Veh. Code § 2413).", url: "https://codes.findlaw.com/ca/civil-code/civ-sect-1798-90-55.html", verified: true},
  {code: "CO", state: "Colorado", statute: "C.R.S. § 24-72-113 (passive surveillance records; general, not ALPR-specific)", summary: "A general rule for government passive-surveillance records such as fixed cameras. It does not name ALPRs. After the first year, access is limited to records tied to a claim or incident. A 2026 ALPR warrant bill (SB26-070) failed.", retention: "3 years (general rule; whether it covers ALPR is unclear)", url: "https://colorado.public.law/statutes/crs_24-72-113", verified: true},
  {code: "CT", state: "Connecticut", statute: "Public Act 26-14 (Subst. SB 397, 2026), §§ 13–15", summary: "From Oct. 1, 2026, public agencies and their vendors may use ALPRs only for listed purposes (hotlists, specific active investigations, warrants, missing persons, parking, tolls and similar). Every search must be logged with a reason. Banned uses: identifying people engaged in First Amendment activity, immigration enforcement, and reproductive or gender-affirming care investigations. Sharing is limited to CT agencies and, with a written declaration, NY, RI or MA agencies. Vendors may not sell data.", retention: "21 days, unless covered by a warrant or court order, active-investigation evidence, or tolling", url: "https://www.cga.ct.gov/2026/ACT/PA/PDF/2026PA-00014-R00SB-00397-PA.PDF", verified: true},
  {code: "FL", state: "Florida", statute: "Fla. Stat. §§ 316.0777, 316.0778", summary: "Police may put ALPRs on state road right-of-way. Data is confidential and exempt from public records, except for criminal justice agencies and a vehicle's own registered owner. ALPRs can't be used to issue traffic citations. The state must set a retention schedule.", retention: "No number in the statute; a maximum is set by the state records retention schedule", url: "https://www.flsenate.gov/Laws/Statutes/2025/316.0778", verified: true},
  {code: "GA", state: "Georgia", statute: "O.C.G.A. § 35-1-22", summary: "Police may use ALPR data only for law enforcement and may share it with other police. It is not subject to public disclosure. Misuse is a high and aggravated misdemeanor.", retention: "30 months, unless tied to a toll violation or a law enforcement purpose", url: "https://codes.findlaw.com/ga/title-35-law-enforcement-officers-and-agencies/ga-code-sect-35-1-22/", verified: true},
  {code: "ID", state: "Idaho", statute: "Idaho Code § 49-1432 (2025)", summary: "Use is limited to criminal investigations, accidents, missing or endangered persons, and traffic-flow analysis. No traffic-infraction enforcement and no personal or political surveillance. Every search is logged and audited twice a year.", retention: "Not specified", url: "https://legislature.idaho.gov/statutesrules/idstat/title49/t49ch14/sect49-1432/", verified: true},
  {code: "IL", state: "Illinois", statute: "625 ILCS 5/2-130 (P.A. 103-540, eff. 1/1/2024); 605 ILCS 140/5 (Expressway Camera Act)", summary: "ALPR users may not share data for investigating immigration status or lawful reproductive or other health care. Out-of-state police need to sign a written declaration first. Separately, state expressway camera images may be used only for listed serious crimes and highway safety.", retention: "No general limit; expressway camera images exported to police: 120 days unless relevant to a case", url: "https://www.ilga.gov/legislation/ilcs/fulltext.asp?DocName=062500050K2-130", verified: true},
  {code: "KY", state: "Kentucky", statute: "KRS 189.632 (2026 Ky. Acts ch. 71, HB 58, eff. 7/15/2026)", summary: "Anyone, including private people, may use ALPRs only for listed purposes. Data can't be sold or shared except with police, by subpoena, or for limited insurance and lending uses. Police must publish a policy, audit every 90 days, and visually confirm a plate before acting on an alert.", retention: "90 days, unless kept for evidence, audit or a subpoena/preservation notice", url: "https://apps.legislature.ky.gov/law/Statutes/statute.aspx?id=57500", verified: true},
  {code: "ME", state: "Maine", statute: "29-A M.R.S. § 2117-A", summary: "Only DOT, State Police and police agencies may use ALPRs, for public safety, commercial-vehicle screening and investigations. Data is confidential and goes only to police. Violations are a Class E crime.", retention: "21 days, unless it is investigative/intelligence or commercial-vehicle data", url: "https://legislature.maine.gov/statutes/29-A/title29-Asec2117-A.html", verified: true},
  {code: "MD", state: "Maryland", statute: "Md. Code, Pub. Safety § 3-509", summary: "ALPR data may be used only for legitimate law enforcement purposes (crime, vehicle law, terrorism, missing persons). Agencies need procedures for access, audits and training. Historical data may not be shared outside the state fusion center. Yearly reporting.", retention: "No fixed period in statute", url: "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gps&section=3-509&enactments=false", verified: true},
  {code: "MN", state: "Minnesota", statute: "Minn. Stat. §§ 13.824, 626.8472", summary: "Police may collect only plate, date, time, location and pictures, and may match only against the state plate file unless there is an active investigation. A central state database is banned. Tracking a specific person needs a warrant. Independent audits every 2 years.", retention: "60 days unless part of an active criminal investigation", url: "https://www.revisor.mn.gov/statutes/cite/13.824", verified: true},
  {code: "MT", state: "Montana", statute: "Mont. Code Ann. §§ 46-5-117 to -119", summary: "ALPR use on public highways is limited to listed agencies and purposes. Data is released only to the vehicle's registered owner, unless that would hurt an investigation.", retention: "90 days; with a preservation request or warrant, up to 1 year per request", url: "https://mca.legmt.gov/bills/mca/title_0460/chapter_0050/part_0010/section_0180/0460-0050-0010-0180.html", verified: true},
  {code: "NE", state: "Nebraska", statute: "Neb. Rev. Stat. §§ 60-3201 to 60-3209", summary: "Use is limited to listed purposes such as parking, access control, tolls and law enforcement. Manual searches need a documented reason. Disclosure is restricted. Users need a privacy policy and police report yearly.", retention: "Government: 180 days unless evidence, a preservation request, or a warrant/subpoena", url: "https://nebraskalegislature.gov/laws/statutes.php?statute=60-3204", verified: true},
  {code: "NH", state: "New Hampshire", statute: "RSA 261:75-b; RSA 236:130", summary: "Government surveillance on public ways is generally banned. Only police may use plate scanners, for listed purposes, and the scanners may not photograph occupants.", retention: "3 minutes, unless the scan leads to an arrest or citation or matches a wanted or missing vehicle", url: "https://gc.nh.gov/rsa/html/XXI/261/261-75-b.htm", verified: true},
  {code: "NJ", state: "New Jersey", statute: "P.L. 2026, c. 4 (N.J.S.A. 52:4CC-1 to -6, approved 3/25/2026); AG Law Enforcement Directive 2022-12", summary: "By statute, government may not sell, share or transfer ALPR data except to other government entities, under a warrant or court order, with the person's consent, or to out-of-state police who certify no civil-immigration use. The AG directive (binding policy, not statute) sets use rules, training and audits.", retention: "Statute: none. AG Directive 2022-12: 3 years unless tied to an active case.", url: "https://www.nj.gov/treasury/pensions/documents/laws/ch4-2026.pdf", verified: true},
  {code: "NM", state: "New Mexico", statute: "Driver Privacy and Safety Act, Laws 2026, ch. 20 (SB 40), eff. 7/1/2026", summary: "Covers all ALPR users. No sharing for immigration enforcement, reproductive or gender-affirming care cases, or targeting protected First Amendment activity. Out-of-state access needs a written declaration. Data is not a public record. Police report yearly.", retention: "None set", url: "https://www.nmlegis.gov/Sessions/26%20Regular/final/SB0040.PDF", verified: true},
  {code: "NC", state: "North Carolina", statute: "N.C. Gen. Stat. §§ 20-183.30 to -183.32", summary: "Agencies need a written policy before deploying. Use is limited to law enforcement. Data is confidential, not a public record, never sold, and shared only with police on written request.", retention: "90 days; a sworn preservation request extends it 1 year (renewable)", url: "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_20/GS_20-183.32.html", verified: true},
  {code: "OK", state: "Oklahoma", statute: "47 O.S. § 7-606.1 (Uninsured Vehicle Enforcement Program)", summary: "Lets a district attorney program use ALPRs to enforce insurance laws. The data may not be sold or used for other purposes. This is not a general ALPR law.", retention: "Unconfirmed", url: "https://oklegislature.gov/cf_pdf/2023-24%20INT/hB/HB3109%20INT.PDF", verified: false},
  {code: "OR", state: "Oregon", statute: "Or. Laws 2026, ch. 77 (SB 1516), §§ 4–9 (effective 3/31/2026)", summary: "Police may use ALPRs only for law enforcement purposes, with search logs. No use that violates Oregon's sanctuary laws. Officers must visually confirm a match before a stop. Vendors may not sell or share the data, and people can sue vendors who do.", retention: "30 days unless related to a court case or ongoing investigation", url: "https://olis.oregonlegislature.gov/liz/2026R1/Downloads/MeasureDocument/SB1516/Enrolled", verified: true},
  {code: "TN", state: "Tennessee", statute: "Tenn. Code Ann. § 55-10-302", summary: "Applies to government entities using fixed ALPR cameras.", retention: "90 days unless part of an ongoing investigation", url: "https://codes.findlaw.com/tn/title-55-motor-and-other-vehicles/tn-code-sect-55-10-302.html", verified: true},
  {code: "UT", state: "Utah", statute: "Utah Code §§ 41-6a-2001 to -2006", summary: "Government ALPR use is banned except for listed purposes (active investigations, warrants, missing persons, stolen vehicles, parking, tolls). Police need a public policy. Data is a protected record and can't be sold. Government needs a warrant or court order to get private ALPR data.", retention: "9 months for government, unless a preservation request, warrant or court order applies", url: "https://le.utah.gov/xcode/Title41/Chapter6A/41-6a-S2004.html", verified: true},
  {code: "VT", state: "Vermont", statute: "23 V.S.A. §§ 1607–1608", summary: "Operators must be certified. Use is limited to legitimate law enforcement purposes. Active data can be searched only for 7 days. Yearly reporting.", retention: "18 months", url: "https://legislature.vermont.gov/statutes/fullchapter/23/015", verified: true},
  {code: "VA", state: "Virginia", statute: "Va. Code § 2.2-5517 (2025 Va. Acts ch. 720, HB 2724)", summary: "Police may use ALPRs only for criminal investigations with reasonable suspicion, missing or endangered persons, human trafficking, and warrant or stolen-vehicle alerts. Sharing with other states, federal agencies or private databases is banned, with listed exceptions. Willful misuse is a Class 1 misdemeanor.", retention: "21 days for system data; 2 years for audit trails (unless part of an ongoing case)", url: "https://law.lis.virginia.gov/vacode/title2.2/chapter55.6/section2.2-5517/", verified: true},
  {code: "WA", state: "Washington", statute: "Ch. 10.130 RCW (Laws of 2026, ch. 239, ESSB 6002 'Driver Privacy Act'), eff. 3/30/2026", summary: "Agency use is limited to serious crimes, stolen vehicles, missing persons, parking and traffic. Banned uses: civil immigration enforcement, health care monitoring, and tracking protected activity. No cameras at schools, places of worship, courts, food banks or care facilities. Agencies may not sell or buy ALPR data, and getting private ALPR data needs a probable-cause warrant. Systems must be registered with the AG.", retention: "21 days unless kept under a warrant, subpoena or court order", url: "https://lawfilesext.leg.wa.gov/biennium/2025-26/Pdf/Bills/Session%20Laws/Senate/6002-S.SL.pdf", verified: true},
];
