/**
 * Public-records (open-records / FOI) laws for all 50 states and the District of Columbia.
 * Researched 2026-10-06 from official statute pages or official state open-government guides
 * (see docs/LEGAL_REVIEW.md). `verified: false` means the official site blocked automated
 * retrieval and the citation rests on secondary sources; the app says so next to the citation.
 * `responseTime` is set only when the official text states a deadline, quoted as written.
 * Information, not legal advice.
 */
export interface RecordsLaw {
  code: string;
  jurisdiction: string;
  lawName: string;
  citation: string;
  requestSection: string | null;
  responseTime: string | null;
  officialUrl: string;
  guideUrl: string | null;
  verified: boolean;
  notes: string;
}

export const RECORDS_LAWS_CHECKED_AT = '2026-10-06';

export const RECORDS_LAWS: RecordsLaw[] = [
  {code: "AL", jurisdiction: "Alabama", lawName: "Alabama Open Records Act", citation: "Ala. Code § 36-12-40 et seq. (§§ 36-12-40, -41 as amended and §§ 36-12-43 to -46 added by Act 2024-278)", requestSection: "Ala. Code § 36-12-40", responseTime: "within 10 days (acknowledge); within 15 business days of acknowledging receipt (substantive response)", officialUrl: "https://alison.legislature.state.al.us/files/pdf/SearchableInstruments/2024RS/SB270-enr.pdf", guideUrl: null, verified: true, notes: "officialUrl is the enrolled SB270 (Act 2024-278, eff. Oct. 1, 2024) on the Alabama Legislature site; the codified-section viewer (ALISON) is JavaScript-only. Deadlines are in new § 36-12-44 for 'standard requests'; responder may extend in 15-business-day increments; time-intensive requests follow a different track (acknowledge within 10 business days). The act changed the right-holder from 'citizen' to 'resident'. Later amendments (2025-26) not checked."},
  {code: "AK", jurisdiction: "Alaska", lawName: "Alaska Public Records Act", citation: "Alaska Stat. § 40.25.110 et seq. (AS 40.25)", requestSection: "Alaska Stat. § 40.25.110", responseTime: null, officialUrl: "https://www.akleg.gov/basis/statutes.asp?media=print&secStart=40.25.110&secEnd=40.25.125", guideUrl: null, verified: true, notes: "Statute says records are open 'under reasonable rules during regular office hours'; no response deadline in the statute text read. A 10-working-day deadline is commonly cited from regulation 2 AAC 96.325 (not verified here; applies to state agencies)."},
  {code: "AZ", jurisdiction: "Arizona", lawName: "Arizona Public Records Law", citation: "A.R.S. § 39-121 et seq. (Title 39, Ch. 1, Art. 2)", requestSection: "A.R.S. § 39-121", responseTime: null, officialUrl: "https://www.azleg.gov/ars/39/00121.htm", guideUrl: "https://www.azoca.gov/public-access-laws/", verified: true, notes: "No fixed deadline; § 39-121.01(D)(1) says the custodian 'shall promptly furnish' copies. Guide is the Arizona Ombudsman-Citizens' Aide public access page."},
  {code: "AR", jurisdiction: "Arkansas", lawName: "Arkansas Freedom of Information Act", citation: "Ark. Code Ann. § 25-19-101 et seq.", requestSection: "Ark. Code Ann. § 25-19-105", responseTime: "within three (3) working days (only if the record is in active use or storage; otherwise available immediately)", officialUrl: "https://arkansasag.gov/divisions/opinions-foia/arkansas-freedom-of-information-act/", guideUrl: "https://media.ark.org/ag/APA-045-2026-FOIA-Handbook-22nd-Edition.pdf", verified: true, notes: "Arkansas Code is hosted by a commercial vendor, so officialUrl is the Attorney General FOIA page ('up to three business days'). The AG's 2026 FOIA Handbook (22nd ed.) reproduces § 25-19-105(e). Personnel/evaluation record requests: 24 hours. Rights run to Arkansas citizens."},
  {code: "CA", jurisdiction: "California", lawName: "California Public Records Act", citation: "Cal. Gov. Code §§ 7920.000–7931.000", requestSection: "Cal. Gov. Code § 7922.525 (inspection); § 7922.530 (copies)", responseTime: null, officialUrl: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=7922.535", guideUrl: null, verified: false, notes: "leginfo.legislature.ca.gov returned HTTP 403 to every automated fetch (curl and WebFetch), so not verified. Secondary sources say § 7922.535 requires a determination 'within 10 days' of a request for copies, extendable up to 14 days in 'unusual circumstances'. Confirm before relying on it. CPRA was renumbered from §§ 6250 et seq. effective 2023."},
  {code: "CO", jurisdiction: "Colorado", lawName: "Colorado Open Records Act (CORA)", citation: "C.R.S. § 24-72-200.1 et seq. (Title 24, Art. 72, Part 2)", requestSection: "C.R.S. § 24-72-203", responseTime: "'reasonable time' presumed to be three working days or less (extendable up to seven working days for extenuating circumstances)", officialUrl: "https://leg.colorado.gov/sites/default/files/images/olls/crs2024-title-24.pdf", guideUrl: "https://coag.gov/media-center/colorado-open-records-act-cora/", verified: true, notes: "Verified from the 2024 C.R.S. Title 24 PDF on leg.colorado.gov (25 MB; CORA text is around p. 2560+). A 2025 bill (SB25-077) to lengthen the deadline to 5 working days was vetoed on 4/17/2025, per news reports; changes enacted in 2026 not checked. The AG's CORA policy page cites the same three-working-day rule."},
  {code: "CT", jurisdiction: "Connecticut", lawName: "Connecticut Freedom of Information Act", citation: "Conn. Gen. Stat. §§ 1-200 to 1-242", requestSection: "Conn. Gen. Stat. § 1-210", responseTime: "within four business days (written denial deadline)", officialUrl: "https://www.cga.ct.gov/current/pub/chap_014.htm", guideUrl: "https://portal.ct.gov/foi", verified: true, notes: "'Four business days' is in § 1-206(a): a denial must be issued in writing within four business days, otherwise the request is deemed denied. It becomes ten business days when § 1-214 (employee records) applies. § 1-210 itself requires 'prompt' access. Guide is the CT Freedom of Information Commission."},
  {code: "DE", jurisdiction: "Delaware", lawName: "Delaware Freedom of Information Act", citation: "29 Del. C. ch. 100 (§§ 10001–10008)", requestSection: "29 Del. C. § 10003", responseTime: "as soon as possible, but in any event within 15 business days", officialUrl: "https://delcode.delaware.gov/title29/c100/index.html", guideUrl: "https://attorneygeneral.delaware.gov/executive/open-government/", verified: true, notes: "§ 10003(h)(1). The body can take more time by citing a statutory reason and giving a good-faith estimate. Chapter 100 also covers open meetings."},
  {code: "DC", jurisdiction: "District of Columbia", lawName: "District of Columbia Freedom of Information Act", citation: "D.C. Code § 2-531 et seq.", requestSection: "D.C. Code § 2-532", responseTime: "within 15 days (except Saturdays, Sundays, and legal public holidays)", officialUrl: "https://code.dccouncil.gov/us/dc/council/code/sections/2-532", guideUrl: "https://dc.gov/page/freedom-information-act-foia", verified: true, notes: "§ 2-532(c)(1). MPD body-worn camera recordings: 25 days. Extensions up to 10 more days (15 for BWC) by written notice."},
  {code: "FL", jurisdiction: "Florida", lawName: "Florida Public Records Act (Chapter 119)", citation: "Fla. Stat. ch. 119; Fla. Const. art. I, § 24", requestSection: "Fla. Stat. § 119.07(1)(a)", responseTime: null, officialUrl: "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0100-0199/0119/Sections/0119.07.html", guideUrl: "https://www.myfloridalegal.com/open-government", verified: true, notes: "No fixed deadline. The statute requires inspection 'at any reasonable time, under reasonable conditions'; courts read this as allowing only the time reasonably needed to retrieve and review records."},
  {code: "GA", jurisdiction: "Georgia", lawName: "Georgia Open Records Act", citation: "O.C.G.A. §§ 50-18-70 to 50-18-77", requestSection: "O.C.G.A. § 50-18-71", responseTime: "within a reasonable amount of time not to exceed three business days", officialUrl: "https://law.georgia.gov/key-issues/open-government/law", guideUrl: "https://law.georgia.gov/document/document/citizens-guide-open-government/download", verified: true, notes: "Georgia Code is hosted by a commercial vendor; officialUrl is the AG's 'The Law' page, which links the statute PDF. The AG's Citizen's Guide reproduces § 50-18-71(b)(1)(A). If records can't be produced in 3 business days, the agency must give a description and a production timetable within that period."},
  {code: "HI", jurisdiction: "Hawaii", lawName: "Uniform Information Practices Act (Modified) (UIPA)", citation: "Haw. Rev. Stat. ch. 92F", requestSection: "Haw. Rev. Stat. § 92F-11", responseTime: null, officialUrl: "https://ags.hawaii.gov/oip/uipa/", guideUrl: "https://ags.hawaii.gov/oip/", verified: true, notes: "capitol.hawaii.gov returned 403, so officialUrl is the Office of Information Practices page, which reproduces the full chapter 92F text. No response deadline in the statute; deadlines (commonly cited as 10 business days) are in OIP administrative rules, HAR ch. 2-71 (not verified here)."},
  {code: "ID", jurisdiction: "Idaho", lawName: "Idaho Public Records Act", citation: "Idaho Code § 74-101 et seq. (Title 74, Ch. 1)", requestSection: "Idaho Code § 74-102", responseTime: "within three (3) working days (residents); within twenty-one (21) days (non-residents)", officialUrl: "https://legislature.idaho.gov/statutesrules/idstat/title74/t74ch1/sect74-103/", guideUrl: null, verified: true, notes: "§ 74-103 now treats residents and non-residents differently. If more time is needed, records are due within 10 working days (residents) or 35 days (non-residents). The resident/non-resident split appears recent; app copy should account for it."},
  {code: "IL", jurisdiction: "Illinois", lawName: "Illinois Freedom of Information Act", citation: "5 ILCS 140", requestSection: "5 ILCS 140/3", responseTime: "within 5 business days", officialUrl: "https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=85&ChapterID=2", guideUrl: "https://illinoisattorneygeneral.gov/open-and-honest-government/", verified: true, notes: "§ 3(d): comply or deny 'promptly ... within 5 business days', extendable by 5 business days under § 3(e). Commercial requests: 21 working days (§ 3.1). Guide is the AG Public Access Counselor area. The ilga.gov URL redirects to /Legislation/ILCS/Articles?ActID=85&ChapterID=2."},
  {code: "IN", jurisdiction: "Indiana", lawName: "Access to Public Records Act (APRA)", citation: "Ind. Code ch. 5-14-3", requestSection: "Ind. Code § 5-14-3-3", responseTime: "within twenty-four (24) hours (in person/telephone); within seven (7) days (mail, fax, or email)", officialUrl: "https://www.in.gov/pac/files/PAC-Handbook-2017.pdf", guideUrl: "https://www.in.gov/pac/", verified: true, notes: "Deadlines are in IC 5-14-3-9 and are deadlines to respond, not to produce; production must happen in a 'reasonable time'. officialUrl is the Public Access Counselor's handbook (2017 edition, may be dated), which quotes the statute. iga.in.gov is JavaScript-only and could not be read."},
  {code: "IA", jurisdiction: "Iowa", lawName: "Iowa Open Records Law", citation: "Iowa Code ch. 22", requestSection: "Iowa Code § 22.2", responseTime: null, officialUrl: "https://www.legis.iowa.gov/docs/code/22.pdf", guideUrl: "https://ipib.iowa.gov/", verified: true, notes: "No general response deadline in ch. 22. § 22.8(4)(d) allows a good-faith delay to decide whether a record is confidential, which 'shall not exceed twenty calendar days and ordinarily should not exceed ten business days'. Guide is the Iowa Public Information Board."},
  {code: "KS", jurisdiction: "Kansas", lawName: "Kansas Open Records Act (KORA)", citation: "K.S.A. 45-215 et seq.", requestSection: "K.S.A. 45-218", responseTime: "not later than the end of the third business day following the date that the request is received", officialUrl: "https://www.ksrevisor.gov/statutes/chapters/ch45/045_002_0018.html", guideUrl: null, verified: true, notes: "K.S.A. 45-218(d): 'acted upon as soon as possible' by that deadline. If access isn't immediate, the custodian must explain the delay and give the earliest date the record will be available."},
  {code: "KY", jurisdiction: "Kentucky", lawName: "Kentucky Open Records Act", citation: "KRS 61.870 to 61.884", requestSection: "KRS 61.872", responseTime: "within five (5) days, excepting Saturdays, Sundays, and legal holidays", officialUrl: "https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=51391", guideUrl: null, verified: true, notes: "Deadline is KRS 61.880(1) (statute.aspx?id=51394). KRS 61.872 now limits the right of inspection to Kentucky residents. Statute pages download as PDFs."},
  {code: "LA", jurisdiction: "Louisiana", lawName: "Louisiana Public Records Law", citation: "La. R.S. 44:1 et seq.", requestSection: "La. R.S. 44:31", responseTime: "within five days, exclusive of Saturdays, Sundays, and legal public holidays (only when the custodian questions whether the record is public)", officialUrl: "https://legis.la.gov/legis/Law.aspx?d=99688", guideUrl: null, verified: true, notes: "R.S. 44:32(D) (Law.aspx?d=99691); the 2022 amendment changed three days to five. If a record isn't immediately available, 44:33 requires the custodian to certify that and set a date (44:33 not read here)."},
  {code: "ME", jurisdiction: "Maine", lawName: "Maine Freedom of Access Act (FOAA)", citation: "1 M.R.S. § 400 et seq.", requestSection: "1 M.R.S. § 408-A", responseTime: "within 5 working days (acknowledgment)", officialUrl: "https://legislature.maine.gov/statutes/1/title1sec408-A.html", guideUrl: "https://www.maine.gov/foaa/", verified: true, notes: "§ 408-A(3): acknowledge within 5 working days, then give a good-faith estimate of time and cost 'within a reasonable time'. No fixed production deadline."},
  {code: "MD", jurisdiction: "Maryland", lawName: "Maryland Public Information Act (PIA)", citation: "Md. Code Ann., Gen. Prov. § 4-101 et seq.", requestSection: "Md. Code Ann., Gen. Prov. § 4-201", responseTime: "promptly, but not more than 30 days after receiving the application", officialUrl: "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=ggp&section=4-203&enactments=false", guideUrl: "https://piaombuds.maryland.gov/", verified: true, notes: "§ 4-203(a)-(b). If production will take more than 10 working days, the custodian must say so in writing within 10 working days. Some requests (§ 4-356) allow 50 days. Guide is the Public Access Ombudsman."},
  {code: "MA", jurisdiction: "Massachusetts", lawName: "Massachusetts Public Records Law", citation: "M.G.L. c. 66, § 10; c. 4, § 7(26)", requestSection: "M.G.L. c. 66, § 10", responseTime: "not later than 10 business days following the receipt of the request", officialUrl: "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleX/Chapter66/Section10", guideUrl: null, verified: true, notes: "§ 10(a)-(b). If the agency can't produce in 10 business days it must say so in writing in that period. Production limit is 15 business days (agency) or 25 business days (municipality) from receipt, and the Supervisor of Records may grant one further extension. The Secretary of the Commonwealth's public records page redirected in a loop when checked, so no guideUrl."},
  {code: "MI", jurisdiction: "Michigan", lawName: "Michigan Freedom of Information Act", citation: "MCL 15.231 et seq.", requestSection: "MCL 15.233", responseTime: "within 5 business days", officialUrl: "https://www.legislature.mi.gov/Laws/MCL?objectName=mcl-15-235", guideUrl: null, verified: true, notes: "MCL 15.235(2): respond (grant, deny, partially grant, or extend) within 5 business days. A written extension can add up to 10 business days."},
  {code: "MN", jurisdiction: "Minnesota", lawName: "Minnesota Government Data Practices Act", citation: "Minn. Stat. ch. 13", requestSection: "Minn. Stat. § 13.03", responseTime: null, officialUrl: "https://www.revisor.mn.gov/statutes/cite/13.03", guideUrl: "https://mn.gov/admin/data-practices/", verified: true, notes: "No fixed deadline for public data requests; § 13.03 subd. 2 requires an 'appropriate and prompt manner'. Data subjects asking for data about themselves get 10 business days under § 13.04 (not read here). guideUrl (Data Practices Office) is behind a bot wall and was not loaded."},
  {code: "MS", jurisdiction: "Mississippi", lawName: "Mississippi Public Records Act of 1983", citation: "Miss. Code Ann. § 25-61-1 et seq.", requestSection: "Miss. Code Ann. § 25-61-5", responseTime: "no later than seven (7) working days (up to fourteen (14) working days with written explanation)", officialUrl: "https://www.ethics.ms.gov/thepublicrecordact", guideUrl: null, verified: true, notes: "Mississippi Code is hosted by a commercial vendor; officialUrl is the Mississippi Ethics Commission page (the enforcing agency), which reproduces chapter 61. Agencies with no written procedures must provide access within one (1) working day."},
  {code: "MO", jurisdiction: "Missouri", lawName: "Missouri Sunshine Law", citation: "Mo. Rev. Stat. ch. 610 (§ 610.010 et seq.)", requestSection: "Mo. Rev. Stat. § 610.023", responseTime: "no later than the end of the third business day following the date the request is received", officialUrl: "https://revisor.mo.gov/main/OneSection.aspx?section=610.023", guideUrl: "https://ago.mo.gov/get-help/programs-services-from-a-z/sunshine-law/", verified: true, notes: "§ 610.023.3: 'acted upon as soon as possible'. Any delay beyond the deadline needs a detailed explanation and the earliest date the records will be available."},
  {code: "MT", jurisdiction: "Montana", lawName: "Montana public records law (constitutional right to know + MCA Title 2, Ch. 6, Part 10)", citation: "Mont. Const. art. II, § 9; Mont. Code Ann. §§ 2-6-1001 to 2-6-1020", requestSection: "Mont. Code Ann. § 2-6-1003", responseTime: null, officialUrl: "https://mca.legmt.gov/bills/mca/title_0020/chapter_0060/part_0100/section_0060/0020-0060-0100-0060.html", guideUrl: null, verified: true, notes: "§ 2-6-1006: local governments must respond 'in a timely manner' (no number). Non-local (state) agencies must acknowledge within 5 business days and meet further deadlines. responseTime left null because surveillance-camera requests usually go to local governments. Right of access is in § 2-6-1003."},
  {code: "NE", jurisdiction: "Nebraska", lawName: "Nebraska Public Records Statutes", citation: "Neb. Rev. Stat. §§ 84-712 to 84-712.09", requestSection: "Neb. Rev. Stat. § 84-712", responseTime: "as soon as is practicable and without delay, but not more than four business days after actual receipt of the request", officialUrl: "https://nebraskalegislature.gov/laws/statutes.php?statute=84-712", guideUrl: "https://ago.nebraska.gov/public-records", verified: true, notes: "§ 84-712(4). If the request can't be met in 4 business days, the custodian must explain in writing and give the earliest practicable date."},
  {code: "NV", jurisdiction: "Nevada", lawName: "Nevada Public Records Act", citation: "NRS ch. 239", requestSection: "NRS 239.010", responseTime: "by the end of the fifth business day after the date on which the person who has legal custody or control of the public book or record received the request", officialUrl: "https://www.leg.state.nv.us/NRS/NRS-239.html", guideUrl: null, verified: true, notes: "Deadline is NRS 239.0107(1)(c). If records can't be provided by then, written notice and a date are required."},
  {code: "NH", jurisdiction: "New Hampshire", lawName: "Right-to-Know Law", citation: "RSA ch. 91-A", requestSection: "RSA 91-A:4", responseTime: "within 5 business days of a request", officialUrl: "https://gc.nh.gov/rsa/html/VI/91-A/91-A-4.htm", guideUrl: null, verified: true, notes: "RSA 91-A:4, IV(b): if the record isn't available immediately, the agency must within 5 business days make it available, deny the request, or state the time needed plus a cost estimate."},
  {code: "NJ", jurisdiction: "New Jersey", lawName: "Open Public Records Act (OPRA)", citation: "N.J.S.A. 47:1A-1 et seq.", requestSection: "N.J.S.A. 47:1A-5", responseTime: "not later than seven (7) business days after the request is received", officialUrl: "https://nj.gov/grc/public/citizens/Citizen's%20Guide%20to%20OPRA%20(Oct%202024)(Final).pdf", guideUrl: "https://www.nj.gov/grc/public/", verified: true, notes: "officialUrl is the Government Records Council's Citizen's Guide (Oct. 2024), which reflects P.L. 2024, c.16. Deadline is § 47:1A-5(i). Commercial-purpose requests get 14 business days, and other exceptions apply. Since Sept. 3, 2024, requests must include certain certifications."},
  {code: "NM", jurisdiction: "New Mexico", lawName: "Inspection of Public Records Act (IPRA)", citation: "NMSA 1978 § 14-2-1 et seq.", requestSection: "NMSA 1978 § 14-2-1", responseTime: null, officialUrl: "https://nmonesource.com/nmos/nmsa/en/nav.do", guideUrl: null, verified: false, notes: "Not verified: nmonesource.com (official NMSA host) and nmdoj.gov both returned 403. An official agency page (NM Regulation & Licensing Dept., rld.nm.gov) describes § 14-2-8: inspection 'immediately or as soon as practicable, but no later than fifteen (15) calendar days', with a written explanation if not allowed within three (3) business days. The NM DOJ publishes an IPRA Compliance Guide (9th ed., 2024), not retrieved."},
  {code: "NY", jurisdiction: "New York", lawName: "Freedom of Information Law (FOIL)", citation: "N.Y. Pub. Off. Law §§ 84–90", requestSection: "N.Y. Pub. Off. Law § 87", responseTime: "within five business days of the receipt of a written request", officialUrl: "https://www.nysenate.gov/legislation/laws/PBO/89", guideUrl: "https://opengovernment.ny.gov/", verified: true, notes: "§ 89(3)(a): within five business days, grant, deny, or acknowledge with an approximate decision date. nysenate.gov blocks curl (403) but WebFetch loaded § 89. guideUrl (Committee on Open Government) returned 403 and was not loaded."},
  {code: "NC", jurisdiction: "North Carolina", lawName: "North Carolina Public Records Act", citation: "N.C. Gen. Stat. ch. 132", requestSection: "N.C. Gen. Stat. § 132-6", responseTime: null, officialUrl: "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByChapter/Chapter_132.html", guideUrl: null, verified: true, notes: "No fixed deadline: § 132-6(a) requires inspection 'at reasonable times' and copies 'as promptly as possible'."},
  {code: "ND", jurisdiction: "North Dakota", lawName: "North Dakota Open Records Law", citation: "N.D.C.C. § 44-04-18 (ch. 44-04)", requestSection: "N.D.C.C. § 44-04-18", responseTime: null, officialUrl: "https://ndlegis.gov/cencode/t44c04.pdf", guideUrl: null, verified: true, notes: "No fixed deadline. § 44-04-18(8) makes it a violation when access is 'denied or unreasonably delayed'. The AG reviews complaints (attorney.nd.gov did not resolve when checked)."},
  {code: "OH", jurisdiction: "Ohio", lawName: "Ohio Public Records Act", citation: "Ohio Rev. Code § 149.43", requestSection: "Ohio Rev. Code § 149.43(B)(1)", responseTime: null, officialUrl: "https://codes.ohio.gov/ohio-revised-code/section-149.43", guideUrl: "https://www.ohioattorneygeneral.gov/Legal/Sunshine-Laws", verified: true, notes: "No fixed deadline: records must be 'promptly prepared' for inspection, and copies provided 'within a reasonable period of time'. Special factors apply to law-enforcement video records."},
  {code: "OK", jurisdiction: "Oklahoma", lawName: "Oklahoma Open Records Act", citation: "51 O.S. § 24A.1 et seq.", requestSection: "51 O.S. § 24A.5", responseTime: null, officialUrl: "https://www.oscn.net/applications/oscn/DeliverDocument.asp?CiteID=80292", guideUrl: "https://www.oklahoma.gov/content/dam/ok/en/oag/open-records/oma-and-ora-resources/Open%20Records%20One%20Pager.pdf", verified: true, notes: "No fixed deadline: § 24A.5(6) requires 'prompt, reasonable access', with delays limited to the time needed to protect records and avoid excessive disruption. OSCN is the Oklahoma courts' official statute host."},
  {code: "OR", jurisdiction: "Oregon", lawName: "Oregon Public Records Law", citation: "ORS 192.311 to 192.478", requestSection: "ORS 192.314", responseTime: "within five business days (acknowledge or complete); complete as soon as reasonably possible but not later than 10 business days after the acknowledgment deadline", officialUrl: "https://www.oregonlegislature.gov/bills_laws/ors/ors192.html", guideUrl: "https://www.doj.state.or.us/oregon-department-of-justice/public-records/public-records-and-meetings-law/", verified: true, notes: "Deadlines are in ORS 192.324(2) and 192.329(5), with statutory exceptions (e.g., large requests, fee payment)."},
  {code: "PA", jurisdiction: "Pennsylvania", lawName: "Right-to-Know Law (RTKL)", citation: "65 P.S. §§ 67.101–67.3104 (Act of Feb. 14, 2008, P.L. 6, No. 3)", requestSection: "65 P.S. § 67.701", responseTime: "shall not exceed five business days from the date the written request is received by the open-records officer", officialUrl: "https://www.openrecords.pa.gov/Documents/RTKL/PA_Right-To-Know_Law.pdf", guideUrl: "https://www.openrecords.pa.gov/RTKL/CitizensGuide.cfm", verified: true, notes: "Section 901 (65 P.S. § 67.901). Agencies may take a 30-calendar-day extension under § 902. officialUrl is the Office of Open Records' copy of the Act (includes amendments effective July 1, 2024). Section numbers in the PDF are Act sections, and 65 P.S. § 67.xxx corresponds."},
  {code: "RI", jurisdiction: "Rhode Island", lawName: "Access to Public Records Act (APRA)", citation: "R.I. Gen. Laws § 38-2-1 et seq.", requestSection: "R.I. Gen. Laws § 38-2-3", responseTime: "within ten (10) business days after receiving a request", officialUrl: "https://webserver.rilegislature.gov/Statutes/TITLE38/38-2/38-2-3.htm", guideUrl: null, verified: true, notes: "§ 38-2-3(e). Extendable by up to 20 more business days for good cause, with written explanation."},
  {code: "SC", jurisdiction: "South Carolina", lawName: "South Carolina Freedom of Information Act", citation: "S.C. Code Ann. § 30-4-10 et seq.", requestSection: "S.C. Code Ann. § 30-4-30", responseTime: "within ten days (excepting Saturdays, Sundays, and legal public holidays)", officialUrl: "https://www.scstatehouse.gov/code/t30c004.php", guideUrl: null, verified: true, notes: "§ 30-4-30(C) sets the deadline to notify the requester of the determination; it is 20 such days if the record is more than 24 months old. Separate production deadlines follow the determination."},
  {code: "SD", jurisdiction: "South Dakota", lawName: "South Dakota Public Records Law", citation: "SDCL ch. 1-27", requestSection: "SDCL § 1-27-1", responseTime: "no later than ten business days from receipt of the request (written requests)", officialUrl: "https://sdlegislature.gov/api/Statutes/1-27-1.html", guideUrl: null, verified: true, notes: "Deadline is SDCL § 1-27-37 and applies to a written request filed after an informal request is denied; otherwise the response may be an acknowledgment with a time estimate. officialUrl is the Legislature's statute API page (the human-facing sdlegislature.gov/Statutes/1-27-1 is JavaScript-rendered)."},
  {code: "TN", jurisdiction: "Tennessee", lawName: "Tennessee Public Records Act", citation: "Tenn. Code Ann. § 10-7-501 et seq.", requestSection: "Tenn. Code Ann. § 10-7-503", responseTime: "within seven (7) business days (if records are not promptly available)", officialUrl: "https://comptroller.tn.gov/office-functions/open-records-counsel/open-meetings/frequently-asked-questions/tennessee-public-records-act-faqs.html", guideUrl: "https://comptroller.tn.gov/office-functions/open-records-counsel.html", verified: true, notes: "Tennessee Code is hosted by a commercial vendor; officialUrl is the Comptroller's Office of Open Records Counsel FAQ, which cites § 10-7-503(a)(2)(B). Only Tennessee citizens have the statutory right of access."},
  {code: "TX", jurisdiction: "Texas", lawName: "Texas Public Information Act (PIA)", citation: "Tex. Gov't Code ch. 552", requestSection: "Tex. Gov't Code § 552.221", responseTime: "promptly; if it will take longer than ten business days, the governmental body must notify the requester when the information will be released", officialUrl: "https://www.texasattorneygeneral.gov/open-government/members-public/overview-public-information-act", guideUrl: "https://www.texasattorneygeneral.gov/open-government", verified: true, notes: "officialUrl is the Attorney General's PIA overview. statutes.capitol.texas.gov is JavaScript-rendered and § 552.221 could not be read directly, so requestSection is from general knowledge. To withhold information the agency must request an AG ruling within 10 business days."},
  {code: "UT", jurisdiction: "Utah", lawName: "Government Records Access and Management Act (GRAMA)", citation: "Utah Code § 63G-2-101 et seq.", requestSection: "Utah Code § 63G-2-201", responseTime: "as soon as reasonably possible, but no later than 10 business days after receiving a written request (five business days if expedited)", officialUrl: "https://le.utah.gov/xcode/Title63G/Chapter2/C63G-2-S204_2023050320230503.html", guideUrl: null, verified: true, notes: "Deadline is § 63G-2-204(4)(b). Expedited (five-day) handling requires showing the request benefits the public. 'Extraordinary circumstances' can extend the deadline. Requests must be written and include specific contact details. le.utah.gov has a TLS chain issue for some clients."},
  {code: "VT", jurisdiction: "Vermont", lawName: "Vermont Public Records Act", citation: "1 V.S.A. § 315 et seq.", requestSection: "1 V.S.A. § 316", responseTime: "not more than three business days", officialUrl: "https://legislature.vermont.gov/statutes/section/01/005/00318", guideUrl: null, verified: true, notes: "§ 318(a) defines 'promptly' as immediately, with little or no delay, and not more than three business days. Extensions are allowed in unusual circumstances."},
  {code: "VA", jurisdiction: "Virginia", lawName: "Virginia Freedom of Information Act", citation: "Va. Code § 2.2-3700 et seq.", requestSection: "Va. Code § 2.2-3704", responseTime: "promptly, but in all cases within five working days of receiving a request", officialUrl: "https://law.lis.virginia.gov/vacode/title2.2/chapter37/section2.2-3704/", guideUrl: null, verified: true, notes: "§ 2.2-3704(B). Seven more work days if the agency responds within five that it needs more time; 60 work days for criminal investigative files. The FOI Advisory Council site returned 503 when checked. The statutory right runs to Virginia citizens (and some media)."},
  {code: "WA", jurisdiction: "Washington", lawName: "Public Records Act", citation: "RCW ch. 42.56", requestSection: "RCW 42.56.080", responseTime: "within five business days of receiving a public record request", officialUrl: "https://app.leg.wa.gov/RCW/default.aspx?cite=42.56.520", guideUrl: "https://www.atg.wa.gov/open-government", verified: true, notes: "RCW 42.56.520(1): respond within five business days by providing records, acknowledging with an estimate, seeking clarification, or denying."},
  {code: "WV", jurisdiction: "West Virginia", lawName: "West Virginia Freedom of Information Act", citation: "W. Va. Code § 29B-1-1 et seq.", requestSection: "W. Va. Code § 29B-1-3", responseTime: "as soon as is practicable but within a maximum of five days not including Saturdays, Sundays or legal holidays", officialUrl: "https://code.wvlegislature.gov/29B-1-3/", guideUrl: null, verified: true, notes: "Within that time the custodian must furnish copies, set a time and place for inspection, or deny in writing."},
  {code: "WI", jurisdiction: "Wisconsin", lawName: "Wisconsin Public Records Law", citation: "Wis. Stat. §§ 19.31–19.39", requestSection: "Wis. Stat. § 19.35", responseTime: null, officialUrl: "https://docs.legis.wisconsin.gov/statutes/statutes/19/II/35", guideUrl: null, verified: true, notes: "No fixed deadline: § 19.35(4)(a) requires a response 'as soon as practicable and without delay'. The DOJ Office of Open Government page URL could not be confirmed (redirect/404)."},
  {code: "WY", jurisdiction: "Wyoming", lawName: "Wyoming Public Records Act", citation: "Wyo. Stat. §§ 16-4-201 to 16-4-205", requestSection: "Wyo. Stat. § 16-4-202", responseTime: "not later than thirty (30) calendar days from the date of acknowledged receipt of the request", officialUrl: "https://wyoleg.gov/statutes/compress/title16.pdf", guideUrl: null, verified: true, notes: "§ 16-4-202(c)-(d): readily available records 'released immediately'. Notices about unavailability are due within seven (7) business days of acknowledged receipt. Good cause allows a mutually agreed date, and complaints go to a governor-designated ombudsman. officialUrl is the full Title 16 PDF."},
];

export const RECORDS_LAW_BY_CODE: Record<string, RecordsLaw> = Object.fromEntries(RECORDS_LAWS.map((l) => [l.code, l]));
