#!/usr/bin/env tsx
/**
 * Proves every legal statement shown in the app maps to the research ledger, and renders
 * docs/LEGAL_REVIEW.md from it.
 *   npx tsx tools/content-check/legal-ledger.ts           # check + write docs/LEGAL_REVIEW.md
 *   npx tsx tools/content-check/legal-ledger.ts --check   # check only (fails if the doc is stale)
 * Rules: every article lead and section has ≥1 row; every row is verified/corrected/product,
 * or "disclosed" only when the section text itself says it is unverified; every cited source
 * exists in the register and (for legal rows) is cited by that section or article; no row may
 * claim attorney review; articles must not be marked attorney-reviewed.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { LEGAL_ARTICLES } from '../../content/legal/legal';
import { REVIEW_ROWS, RESIDUAL_RISKS, REVIEW_CHECKED_AT, REVIEW_METHOD } from '../../content/legal/review';
import { SOURCE_BY_ID } from '../../content/sources';
import { RECORDS_LAWS } from '../../content/legal/recordsLaws';

const ROOT = join(import.meta.dirname, '..', '..');
const problems: string[] = [];
const units: { article: string; section: string; text: string; sourceIds: string[] }[] = [];
for (const a of LEGAL_ARTICLES) {
  if (a.reviewStatus !== 'not_attorney_reviewed') problems.push(`${a.id}: marked attorney-reviewed`);
  units.push({ article: a.id, section: 'lead', text: a.lead, sourceIds: a.sourceIds });
  for (const s of a.sections) units.push({ article: a.id, section: s.id, text: s.body, sourceIds: s.sourceIds });
}
for (const u of units) {
  const rows = REVIEW_ROWS.filter((r) => r.article === u.article && r.section === u.section);
  if (!rows.length) problems.push(`${u.article}/${u.section}: no ledger row`);
  for (const r of rows) {
    if (r.status === 'disclosed' && !/unverified|could not be confirmed/i.test(u.text)) problems.push(`${u.article}/${u.section}: disclosed row but the text does not say it is unverified`);
    if (r.status !== 'product' && r.status !== 'disclosed' && r.sourceIds.length === 0 && u.section !== 'lead') problems.push(`${u.article}/${u.section}: legal row without a source`);
    for (const id of r.sourceIds) {
      if (!SOURCE_BY_ID[id]) problems.push(`${u.article}/${u.section}: unknown source ${id}`);
      else if (!u.sourceIds.includes(id) && !LEGAL_ARTICLES.find((a) => a.id === u.article)!.sourceIds.includes(id)) problems.push(`${u.article}/${u.section}: row cites ${id} but the section does not`);
    }
    if (!r.pinpoint.trim()) problems.push(`${u.article}/${u.section}: empty pinpoint`);
  }
}
for (const r of REVIEW_ROWS) if (!units.some((u) => u.article === r.article && u.section === r.section)) problems.push(`ledger row for missing section ${r.article}/${r.section}`);
const allText = units.map((u) => u.text).join('\n');
if (/attorney[- ]reviewed(?! ?·)/i.test(allText.replace(/not (be )?(attorney|lawyer)[- ]reviewed/gi, ''))) problems.push('legal text claims attorney review');

const counts = REVIEW_ROWS.reduce<Record<string, number>>((m, r) => ((m[r.status] = (m[r.status] ?? 0) + 1), m), {});
const src = (id: string) => (SOURCE_BY_ID[id] ? `[${id}](${SOURCE_BY_ID[id].url})` : id);
const md = [
  '# Legal research ledger',
  '',
  `Generated by \`tools/content-check/legal-ledger.ts\` from \`content/legal/review.ts\`. Checked ${REVIEW_CHECKED_AT}.`,
  '',
  '**This is research, not legal advice, and no lawyer has reviewed it.** It records, claim by claim, where each legal statement in the app comes from, so a reader (or a lawyer later) can check it quickly.',
  '',
  `Method: ${REVIEW_METHOD}`,
  '',
  `Rows: ${REVIEW_ROWS.length} — ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')}. Public-records laws: ${RECORDS_LAWS.length} jurisdictions, ${RECORDS_LAWS.filter((l) => l.verified).length} verified against official text.`,
  '',
  '## Residual risks',
  '',
  ...RESIDUAL_RISKS.map((r) => `- ${r}`),
  '',
  ...LEGAL_ARTICLES.flatMap((a) => [
    `## ${a.title}`,
    '',
    '| Section | Claim | Status | Sources | Where it is supported |',
    '|---|---|---|---|---|',
    ...REVIEW_ROWS.filter((r) => r.article === a.id).map((r) => `| ${r.section} | ${r.claim.replace(/\|/g, '/')} | ${r.status} | ${r.sourceIds.map(src).join(', ') || '—'} | ${r.pinpoint.replace(/\|/g, '/')} |`),
    '',
  ]),
  '## Public-records laws (request builder)',
  '',
  '| Jurisdiction | Law | Citation | Response time in the law | Verified | Source |',
  '|---|---|---|---|---|---|',
  ...RECORDS_LAWS.map((l) => `| ${l.jurisdiction} | ${l.lawName} | ${l.citation} | ${l.responseTime ?? '—'} | ${l.verified ? 'yes' : '**no**'} | [official](${l.officialUrl}) |`),
  '',
].join('\n');
const docPath = join(ROOT, 'docs', 'LEGAL_REVIEW.md');
if (process.argv.includes('--check')) {
  if (!existsSync(docPath) || readFileSync(docPath, 'utf8') !== md) problems.push('docs/LEGAL_REVIEW.md is stale — run without --check');
} else writeFileSync(docPath, md);

console.log(`${units.length} legal statements in ${LEGAL_ARTICLES.length} articles; ${REVIEW_ROWS.length} ledger rows (${Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(', ')})`);
if (problems.length) {
  for (const p of problems) console.log('FAIL', p);
  process.exit(1);
}
console.log('LEGAL LEDGER COMPLETE');
